title:              Clarence
tagline:            on GitHub Pages
description:        Content-focused template for a blog hosted on GitHub Pages.
url:                http://clarencechiang0411.github.io

author:
  name:             Clarence Chiang
  email:            chiang.shihchi@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
      
url: "https://clarencechiang0411.github.io" # the base hostname & protocol for your site

remote_theme:
  "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
